/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    ActionDetails: typeof import('./src/components/ActionDetails.vue')['default']
    RuleConfiguration: typeof import('./src/components/RuleConfiguration.vue')['default']
  }
}
